# Generated by Django 2.2.13 on 2020-08-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0007_sourcerecord_parse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_atty_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_atty_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_atty_organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_atty_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_bar_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
