# Generated by Django 2.2.13 on 2020-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0008_auto_20200818_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_atty_address',
            new_name='default_atty_address_line_one',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_atty_address_line_two',
            field=models.CharField(default='', max_length=200),
        ),
    ]
