# Generated by Django 2.2.13 on 2020-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0009_auto_20200819_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_atty_address_line_one',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_atty_address_line_two',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_atty_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_atty_organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_atty_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_bar_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
