# Generated by Django 2.2.13 on 2020-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0010_auto_20200901_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='raw_text',
            field=models.TextField(null=True),
        ),
    ]
